<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Jellyfin.Plugin.AnimeSama</AssemblyName>
    <RootNamespace>Jellyfin.Plugin.AnimeSama</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.0.0</Version>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <!--
      PrivateAssets="all" : les assemblies Jellyfin/ASP.NET ne sont pas copiées dans le output.
      Elles sont déjà présentes sur le serveur Jellyfin.
    -->
    <PackageReference Include="Jellyfin.Controller" Version="10.9.11" PrivateAssets="all" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Configuration\configPage.html" />
  </ItemGroup>

</Project>
