services:

  anime_sama:
    build:
      context: .
      args:
        VITE_API_URL: https://anime.gihamos.fr
    container_name: anime_sama
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGODB_URL: ${MONGODB_URL}
      API_BASE: https://anime.gihamos.fr
      ADMIN_PORT: "8001"
    volumes:
      - downloads:/tmp/anime_downloads
    networks:
      - proxy_net

  shop_backend:
    build:
      context: .
      dockerfile: shop_backend/Dockerfile
      args:
        VITE_API_URL: https://shop.gihamos.fr
    container_name: anime_sama_shop
    restart: unless-stopped
    env_file:
      - shop_backend/.env
    environment:
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_DB: anime_sama_shop
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
    name: nginx-proxy-manager_default

volumes:
  downloads: